default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  

development:
  <<: *default
  database: furnas_climate_basis_development


production:
  <<: *default
  host:     <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  port:     <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>