default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  pool: 40
  database: furnas_climate_basis_development


production:
  <<: *default
  prepared_statements: false
  advisory_locks: false
  host:     <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  port:     <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>